# Generated by Django 4.1.5 on 2023-01-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_number", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=50)),
                ("publisher", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=100)),
                ("inventory", models.SmallIntegerField()),
                ("available", models.SmallIntegerField()),
                ("language", models.CharField(max_length=100)),
                ("notes", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_out", models.DateTimeField(auto_now_add=True)),
                ("borrower_name", models.CharField(max_length=50)),
                ("borrower_email", models.EmailField(max_length=50)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book",
                        to="libraryapp.book",
                    ),
                ),
            ],
        ),
    ]
