# Generated by Django 4.1.5 on 2023-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
