# Generated by Django 4.1.5 on 2023-01-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryapp", "0004_borrow_delete_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrow",
            old_name="date",
            new_name="checked_out",
        ),
    ]
